alter table if exists company_address drop constraint if exists FKcct0cw50hai1l4eaunparc3a5;
alter table if exists company_event drop constraint if exists FKl4v0u7fostalqyh5vp1uumc0e;
alter table if exists company_file drop constraint if exists FK8fekravfef439ico7ifcloq85;
alter table if exists company_gst drop constraint if exists FK1p0qfij71hbt46ob2njaqy5r0;
alter table if exists company_holiday drop constraint if exists FK165ej7visymb9brao78j7jpb8;
alter table if exists company_image drop constraint if exists FKo1sjbjm5jjkthg1mn9284tj5l;
alter table if exists company_notes drop constraint if exists FKkmw6lhdnx3fxk3qc9kdd226nn;
alter table if exists company_policy drop constraint if exists FK1aprc8xnqbycd36vce71ch83l;
alter table if exists theme drop constraint if exists FK6oop0phr077nfmmmck0m4umn9;
drop table if exists company cascade;
drop table if exists company_address cascade;
drop table if exists company_event cascade;
drop table if exists company_file cascade;
drop table if exists company_gst cascade;
drop table if exists company_holiday cascade;
drop table if exists company_image cascade;
drop table if exists company_notes cascade;
drop table if exists company_policy cascade;
drop table if exists task cascade;
drop table if exists theme cascade;
alter table if exists company_address drop constraint if exists FKcct0cw50hai1l4eaunparc3a5;
alter table if exists company_event drop constraint if exists FKl4v0u7fostalqyh5vp1uumc0e;
alter table if exists company_file drop constraint if exists FK8fekravfef439ico7ifcloq85;
alter table if exists company_gst drop constraint if exists FK1p0qfij71hbt46ob2njaqy5r0;
alter table if exists company_holiday drop constraint if exists FK165ej7visymb9brao78j7jpb8;
alter table if exists company_image drop constraint if exists FKo1sjbjm5jjkthg1mn9284tj5l;
alter table if exists company_notes drop constraint if exists FKkmw6lhdnx3fxk3qc9kdd226nn;
alter table if exists company_policy drop constraint if exists FK1aprc8xnqbycd36vce71ch83l;
alter table if exists theme drop constraint if exists FK6oop0phr077nfmmmck0m4umn9;
drop table if exists company cascade;
drop table if exists company_address cascade;
drop table if exists company_event cascade;
drop table if exists company_file cascade;
drop table if exists company_gst cascade;
drop table if exists company_holiday cascade;
drop table if exists company_image cascade;
drop table if exists company_notes cascade;
drop table if exists company_policy cascade;
drop table if exists task cascade;
drop table if exists theme cascade;
alter table if exists company_address drop constraint if exists FKcct0cw50hai1l4eaunparc3a5;
alter table if exists company_event drop constraint if exists FKl4v0u7fostalqyh5vp1uumc0e;
alter table if exists company_file drop constraint if exists FK8fekravfef439ico7ifcloq85;
alter table if exists company_gst drop constraint if exists FK1p0qfij71hbt46ob2njaqy5r0;
alter table if exists company_holiday drop constraint if exists FK165ej7visymb9brao78j7jpb8;
alter table if exists company_image drop constraint if exists FKo1sjbjm5jjkthg1mn9284tj5l;
alter table if exists company_notes drop constraint if exists FKkmw6lhdnx3fxk3qc9kdd226nn;
alter table if exists company_policy drop constraint if exists FK1aprc8xnqbycd36vce71ch83l;
alter table if exists theme drop constraint if exists FK6oop0phr077nfmmmck0m4umn9;
drop table if exists company cascade;
drop table if exists company_address cascade;
drop table if exists company_event cascade;
drop table if exists company_file cascade;
drop table if exists company_gst cascade;
drop table if exists company_holiday cascade;
drop table if exists company_image cascade;
drop table if exists company_notes cascade;
drop table if exists company_policy cascade;
drop table if exists task cascade;
drop table if exists theme cascade;
alter table if exists company_address drop constraint if exists FKcct0cw50hai1l4eaunparc3a5;
alter table if exists company_event drop constraint if exists FKl4v0u7fostalqyh5vp1uumc0e;
alter table if exists company_file drop constraint if exists FK8fekravfef439ico7ifcloq85;
alter table if exists company_gst drop constraint if exists FK1p0qfij71hbt46ob2njaqy5r0;
alter table if exists company_holiday drop constraint if exists FK165ej7visymb9brao78j7jpb8;
alter table if exists company_image drop constraint if exists FKo1sjbjm5jjkthg1mn9284tj5l;
alter table if exists company_notes drop constraint if exists FKkmw6lhdnx3fxk3qc9kdd226nn;
alter table if exists company_policy drop constraint if exists FK1aprc8xnqbycd36vce71ch83l;
alter table if exists theme drop constraint if exists FK6oop0phr077nfmmmck0m4umn9;
drop table if exists company cascade;
drop table if exists company_address cascade;
drop table if exists company_event cascade;
drop table if exists company_file cascade;
drop table if exists company_gst cascade;
drop table if exists company_holiday cascade;
drop table if exists company_image cascade;
drop table if exists company_notes cascade;
drop table if exists company_policy cascade;
drop table if exists task cascade;
drop table if exists theme cascade;
