alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
alter table company_account drop constraint FKpkhi6byf71hk9qfeuoy5ertg7
alter table company_address drop constraint FKcct0cw50hai1l4eaunparc3a5
alter table company_gst drop constraint FK1p0qfij71hbt46ob2njaqy5r0
alter table company_image drop constraint FKo1sjbjm5jjkthg1mn9284tj5l
alter table company_policy drop constraint FK1aprc8xnqbycd36vce71ch83l
alter table theme drop constraint FK6oop0phr077nfmmmck0m4umn9
drop table if exists company cascade
drop table if exists company_account cascade
drop table if exists company_address cascade
drop table if exists company_gst cascade
drop table if exists company_image cascade
drop table if exists company_policy cascade
drop table if exists theme cascade
