spring:
  profiles:
    active: dev-ide

  application:
    name: lnf-company-service

KEYCLOAK_HOST: "keycloak:8080"

aws:
  s3:
    bucket:
      enabled: true
      service: "/lnf/file"
      folderName: "company"
      financialYear: "2023-24"
      companyCode: "TF"
      salaryConfigFile: "SalaryConfigurations.json"
      investment:
        declaration:
          file: "investment_declaration.json"


application:
  maxInMemorySize: 10485760

connection:
  timeout: 2000

server:
  port: 8082
  servlet:
    context-path: /api/v1

file:
  service:
    url: "http://localhost:8081/api/v1"

# Metrics Configuration
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    jmx:
      exposure:
        exclude: shutdown
        include: "*"
    web:
      exposure:
        exclude:
        include: "*"
logging:
  level:
    org:
      springframework: INFO

springdoc:
  api-docs:
    path: /lnf-company
  swagger-ui:
    path: /lnf-company-api.html
    enabled: true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:company_db
    username: company_user
    password: company@12345
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: drop-and-create
            scripts:
              action: drop-and-create
              create-target: schema.sql
              drop-target: drop-schema.sql
              create-source: metadata
              drop-source: metadata
              create-database-schemas: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}/auth/realms/lnf
          jwk-set-uri: http://${KEYCLOAK_HOST}/auth/realms/lnf/protocol/openid-connect/certs
      client:
        registration:
          company-service:
            client-id: lnf-company-api
            client-secret: ${client-secret:lnf-company-api-secret}
            scope: openid,profile,roles
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST}/auth/realms/lnf

printStackTrace: true

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    #    url: jdbc:postgresql://${database.host:ec2-34-202-158-22.compute-1.amazonaws.com}:${database.port:5432}/${database.name:tsdb}
    url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.name:company_db}
    username: ${database.username:company_user}
    password: ${database.password:company@12345}
    data: classpath*:db/data.sql
    driverClassName: ${database.drive:org.postgresql.Driver}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              create-database-schemas: false
              create-target: schema.sql
              create-source: metadata
              drop-target: drop-schema.sql
              drop-source: metadata
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}/auth/realms/lnf
          jwk-set-uri: http://${KEYCLOAK_HOST}/auth/realms/lnf/protocol/openid-connect/certs
      client:
        registration:
          company-service:
            client-id: lnf-company-api
            client-secret: ${client-secret:lnf-company-api-secret}
            scope: openid,profile,roles
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST}/auth/realms/lnf
printStackTrace: true
---
spring:
  config:
    activate:
      on-profile: dev-ide

  datasource:
    url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.name:company_db}
    username: ${database.username:company_user}
    password: ${database.password:company@12345}
    data: classpath*:db/data.sql
    driverClassName: ${database.drive:org.postgresql.Driver}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              create-database-schemas: false
              create-target: schema.sql
              create-source: metadata
              drop-target: drop-schema.sql
              drop-source: metadata
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true

  autoconfigure:
    exclude:
      - org.keycloak.adapters.springboot.KeycloakAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

printStackTrace: true
---